CREATE TABLE urban (
	FIPS INT,
	POP2010 FLOAT,
	OHU2010 FLOAT,
	TractLOWI FLOAT,
	TractKids FLOAT,
	TractSeniors FLOAT,
	TractWhite FLOAT,
	TractBlack FLOAT,
	TractAsian FLOAT,
	TractNHOPI FLOAT,
	TractAIAN FLOAT,
	TractOMultir FLOAT,
	TractHispanic FLOAT,
	TractHUNV FLOAT,
	PoveryRate FLOAT,
	MedianFamilyIncome FLOAT,
	LA1and10 FLOAT,
	LAhalfand10 FLOAT,
	LA1and20 FLOAT,
	LATracts_half FLOAT,
	LATracts1 FLOAT,
	LATracts10 FLOAT,
	LATracts20 FLOAT,
	County TEXT,
	State TEXT,
	Percentage FLOAT
);

CREATE TABLE rural (
	FIPS TEXT,
	POP2010 FLOAT,
	OHU2010 FLOAT,
	TractLOWI FLOAT,
	TractKids FLOAT,
	TractSeniors FLOAT,
	TractWhite FLOAT,
	TractBlack FLOAT,
	TractAsian FLOAT,
	TractNHOPI FLOAT,
	TractAIAN FLOAT,
	TractOMultir FLOAT,
	TractHispanic FLOAT,
	TractHUNV FLOAT,
	PoveryRate FLOAT,
	MedianFamilyIncome FLOAT,
	LA1and10 FLOAT,
	LAhalfand10 FLOAT,
	LA1and20 FLOAT,
	LATracts_half FLOAT,
	LATracts1 FLOAT,
	LATracts10 FLOAT,
	LATracts20 FLOAT,
	County TEXT,
	State TEXT,
	Percentage FLOAT
);
